Add files via upload

diff --git a/scripts/puff b/scripts/puff
--- a/scripts/puff
+++ b/scripts/puff
@@ -49,12 +49,28 @@ else
 				if [[ ${source[$i]} == *commit=* ]]; then
 					git clone $url $ashtray/$cig/src/$name
 					git -C $ashtray/$cig/src/$name checkout $commit
+					echo "Skipping GPG Verification, using commit."
 				elif [[ ${source[$i]} == *tag=* ]]; then
 					git clone --branch $tag $url $ashtray/$cig/src/$name
+					if [[ -n $(cd $ashtray/$cig/src/$name && git tag -v $tag 2>&1 | grep ${validpgpkeys[$i]}) ]]; then
+						echo "Verified GPG key for $name!"
+					else
+						echo "GPG VERIFICATION FAILED FOR $name!"
+						echo
+						exit 1
+					fi
 				elif [[ ${source[$i]} == *branch=* ]]; then
 					git clone --branch $branch $url $ashtray/$cig/src/$name
+					echo
+					echo "SKIPPING GPG VERIFICATION DUE TO USE OF BRANCH FOR $name!"
+					echo "BE WARNED!"
+					echo
 				else
 					git clone $url $ashtray/$cig/src/$name
+					echo
+					echo "SKIPPING GPG VERIFICATION FOR $name: NO FRAGMENTS!"
+					echo "BE WARNED!"
+					echo
 				fi
 			else
 				if [[ ${source[$i]} == *::* ]]; then
@@ -87,8 +103,10 @@ else
 				else
 					actual=""
 					expected="SKIP"
+					echo
 					echo "SKIPPING CHECKSUM FOR $name!"
 					echo "BE WARNED!"
+					echo
 				fi
 				actual=${actual%%\ *}
 				if [[ $actual == $expected ]]; then
