Add files via upload

diff --git a/scripts/smoke b/scripts/smoke
--- a/scripts/smoke
+++ b/scripts/smoke
@@ -11,7 +11,34 @@ if [[ -z "$@" ]]; then
 else
         cigs=""
         for cig in "$@"; do
-                if [ -d /var/lib/drag/smoked/$cig ]; then
+		if [ $cig == ca-certificates ]; then
+                        echo "Smoking ca-certificates"
+                        mkdir -p $ashtray/$cig/src
+                        cd $ashtray/$cig/src
+                        curl -Lqo ca-certificates.crt https://curl.se/ca/cacert.pem
+                        curl -Lqo certsha256sum       https://curl.se/ca/cacert.pem.sha256
+                        actual=$(sha256sum ca-certificates.crt)
+                        actual=${actual%%\ *}
+                        if [[ "$(cat certsha256sum)" == *$actual* ]]; then
+                                echo "Verified ca-certificates"
+                                echo
+                                if command -v sudo >/dev/null 2>&1; then
+                                        SUDO=sudo
+                                elif command -v doas >/dev/null 2>&1; then
+                                        SUDO=doas
+                                elif command -v su >/dev/null 2>&1; then
+                                        SUDO="su root"
+                                fi 
+                                $SUDO bash -c "set -e
+                                cp ca-certificates.crt /etc/ssl/certs/
+                                cp ca-certificates.crt /etc/ssl/cert.pem"
+                                cigs="$cigs $cig,"
+                        else
+                                echo "CHECKSUM VALIDATION FAILED FOR ca-certificates!"
+                                echo
+                                exit 1
+                        fi
+                elif [ -d /var/lib/drag/smoked/$cig ]; then
                         echo
                         echo "$cig has already been smoked"
                         echo
diff --git a/scripts/stash b/scripts/stash
--- a/scripts/stash
+++ b/scripts/stash
@@ -12,36 +12,38 @@ else
 	cigs=""
 	for cig in "$@"; do
 		echo "Taking a drag..."
-		tmp1=$(mktemp)
-		tmp2=$(mktemp)
-		wget -O $tmp1 https://gitlab.archlinux.org/archlinux/packaging/packages/$cig/-/archive/main/$cig-main.tar.gz 2>&1 | grep -q "302 Found" &&
-		wget -qO $tmp2 https://aur.archlinux.org/cgit/aur.git/snapshot/$cig.tar.gz
-		if file $tmp1 | grep -q "gzip"; then
-			echo "Stashing $cig from Arch's repo..."
+		tmp=$(mktemp)
+		curl -Lo $tmp https://gitlab.archlinux.org/archlinux/packaging/packages/$cig/-/archive/main/$cig-main.tar.gz
+		if file $tmp | grep -q "gzip"; then
+			echo "Stashed $cig from Arch's repo"
 			cigs="$cigs $cig,"
 			if [ -d $stash/$cig ]; then
 				rm -rf $stash/$cig
 			fi
-			tar -xzf $tmp1 -C $stash/
+			tar -xzf $tmp -C $stash/
 			mv $stash/$cig-main $stash/$cig
-		elif file $tmp2 | grep -q "gzip"; then
-			echo "Stashing $cig from the AUR..."
-			cigs="$cigs $cig,"
-			if [ -d $stash/$cig ]; then
-				rm -rf $stash/$cig
-			fi
-			tar -xzf $tmp2 -C $stash/
 		else
-			echo
-			echo "Could not find $cig in Arch's main repo or the AUR!"
-			cigs="${cigs%%,}"
-			if [[ -n "$cigs" ]]; then
-				echo "Stashed$cigs"
+			rm $tmp
+			curl -Lo $tmp https://aur.archlinux.org/cgit/aur.git/snapshot/$cig.tar.gz
+			if file $tmp | grep -q "gzip"; then
+				echo "Stashed $cig from the AUR"
+				cigs="$cigs $cig,"
+				if [ -d $stash/$cig ]; then
+					rm -rf $stash/$cig
+				fi
+				tar -xzf $tmp -C $stash/
+			else
+				echo
+				echo "Could not find $cig in Arch's main repo or the AUR!"
+				cigs="${cigs%%,}"
+				if [[ -n "$cigs" ]]; then
+					echo "Stashed$cigs"
+				fi
+				echo
+				exit 1
 			fi
-			echo
-			exit 1
 		fi
-		rm $tmp1 $tmp2
+		rm $tmp
 	done
 	cigs="${cigs%%,}"
 	snoop $@
